learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('logs_app.urls')),
    
]

logs_app/urls.py
"""Defines URL patterns for logs_app"""

from django.urls import path

from . import views

app_name = 'logs_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<str:topic_name>/', views.topic, name="topic"),
    path('new-topic/', views.new_topic, name='new_topic'),
    path('topics/<str:topic_name>/new-entry/', views.new_entry, name='new_entry'),
    path('topics/<str:topic_name>/<int:entry_id>/', views.edit_entry, name='edit_entry')

]

logs_app/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    """Category of something learned"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the entry"""
        return self.text[:50] + '...'

logs_app/forms.py
from django import forms

from logs_app.models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta():
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta():
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

logs_app/views.py
#render function pulls from 'templates' folder in directory
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Topic
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """The home page for logs_app"""
    return render(request, 'index.html')

def topics(request):
    """Show all topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics.html', context)

def topic(request, topic_name):
    """Detail page for one topic"""
    topic = Topic.objects.get(text=topic_name)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'topic.html', context)

def new_topic(request):
    """Allow the user to create a new topic"""
    if request.method != 'POST':
        # It's a GET-no data submitted
        form = TopicForm()
        context = {'form': form}
        return render(request, 'new_topic.html', context)
    else:
        #It's a POST-send data to database
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('logs_app:topics'))

def new_entry(request, topic_name):
    """Create a new entry in a topic"""
    
    topic = Topic.objects.get(text=topic_name)
    
    if request.method != 'POST':
        #Return blank form
        form = EntryForm()
        context = {'topic': topic, 'form': form}
        return render(request, 'new_entry.html', context)
    else:
        #Send to database
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic

            new_entry.save()

            return HttpResponseRedirect(reverse('logs_app:topic', args=[topic_name]))

def edit_entry(request, topic_name, entry_id):
    """Load current content of an entry and allow it to be changed"""
    pass

logs_app/templates/base.html
  <h1 style="text-align: center"><a href="{% url 'logs_app:index' %}">Learning Log</a> - <a href="{% url 'logs_app:topics' %}">Topics</a></h1>

  {% block content %} 
  
  {% endblock content %}

logs_app/templates/edit_entry.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center;">{{ topic.text }}</h2>
    <h2 style="text-align: center;">Edit an entry</h2>
    
    <form action="{% url 'logs_app:edit_entry' topic.text entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

logs_app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <p style="text-align: center;">Learning log helps you keep track of your learning
        for any topic you're learning about.</p>
{% endblock content %}

logs_app/templates/new_entry.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center;">{{ topic.text }}</h2>
    <h2 style="text-align: center;">Add a new entry</h2>
    
    <form action="{% url 'logs_app:new_entry' topic.text %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>
{% endblock content %}

logs_app/templates/new_topic.html
{% extends "base.html" %}

{% block content %}
    <h2 style="text-align: center;">Add a new topic</h2>

    <form action="{% url 'logs_app:new_topic' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Topic</button>
    </form>
{% endblock content %}

logs_app/templates/topic.html
{% extends 'base.html' %}

{% block content %}
<h2 style="text-align: center;">{{ topic }}</h2>

<h3 style="text-align: center;">Entries</h2>
<h3 style="text-align: right;"><a href="{% url 'logs_app:new_entry' topic.text %}">Add new entry</a></h2>

<ul style="text-align: center; list-style: inside">
    {% for entry in entries %}
        <li style="text-align: center;">
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>
        {% empty %}
            <li>There are no entries for this topic yet</li>
    {% endfor %}
</ul>

{% endblock content %}

logs_app/templates/topics.html
{% extends "base.html" %}

{% block content %}
    <h2 style="text-align: center;">Topics</h2>
    <h2 style="text-align: right;"><a href="{% url 'logs_app:new_topic' %}">Add a new topic</a></h2>

    <ul style="text-align: center; list-style: inside">
        {% for topic in topics %}
            <li style="text-align: center;"><a href="{% url 'logs_app:topic' topic.text %}">{{ topic }}</a></li>
            {% empty %}
                <li>No topics have been added yet</li>
        {% endfor %}
    </ul>

{% endblock content %}